services:
  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          memory: 16M
        limits:
          memory: 128M
      placement:
        constraints:
          - node.role == manager

  db:
    image: mariadb:lts
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 5s
      retries: 10
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - internal
    secrets:
      - mariadb_root_password
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  db-admin:
    image: bitnami/phpmyadmin:5
    environment:
      - DATABASE_HOST=db
    networks:
      - public
      - internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=public"
        - "traefik.http.routers.db-admin.rule=Host(`pma.${ROOT_DOMAIN}`)"
        - "traefik.http.routers.db-admin.entrypoints=https"
        - "traefik.http.routers.db-admin.tls.certresolver=le"
        - "traefik.http.routers.db-admin.middlewares=db-admin-auth"
        - "traefik.http.middlewares.db-admin-auth.basicauth.users=${DB_ADMIN_AUTH}"
        - "traefik.http.services.db-admin.loadbalancer.server.port=8080"
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M


  traefik:
    image: traefik:v3
    configs:
      - source: traefik.yml
        target: /etc/traefik/traefik.yml
      - source: dynamic.yml
        target: /etc/traefik/dynamic.yml
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    # secrets:
    #   - cloudflare.crt
    #   - cloudflare.key
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.dashboard-auth.basicauth.users=${DASHBOARD_AUTH}"
        - "traefik.http.routers.dashboard.rule=Host(`admin.${ROOT_DOMAIN}`)"
        - "traefik.http.routers.dashboard.entrypoints=https"
        - "traefik.http.routers.dashboard.tls.certresolver=le"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      replicas: 1
      resources:
        reservations:
          memory: 32M
        limits:
          memory: 64M
      placement:
        constraints:
          - node.role == manager

volumes:
  redis-data:
  mariadb-data:
  letsencrypt:
    
configs:
  traefik.yml:
    name: traefik.yml_${STACK_VERSION:-0}
    file: traefik/traefik.yml
  dynamic.yml:
    name: dynamic.yml_${STACK_VERSION:-0}
    file: traefik/dynamic.yml

secrets:
  mariadb_root_password:
    name: mariadb_root_password
    external: true
  # cloudflare.crt:
  #   name: cloudflare.crt
  #   external: true
  # cloudflare.key:
  #   name: cloudflare.key
  #   external: true

networks:
  internal:
    name: internal
    driver: overlay
  public:
    name: public
    driver: overlay
